### ISSUE TITLE
Any benchmarks?

### ISSUE THREAD

**Issue by warrenrentlytics** [furunkel/awasm#3]
Is there any data on how this system compares to a similar setup but using a conventional interpreter/none-machine code approach? I know there are papers from the 90s showing machine code to yield massive performance gains. Has that been measured here on modern hardware at all? Thanks!

**Comment by furunkel** [comment]
No, unfortunately not. It will obviously depend on the number of samples; there is a break even point. But for the usual sample set size I'd presume it's actually slower: first encoding x86 is costly. Secondly there are code caching issues: modifying machine code kills the μop cache, so the CPU has to re-decode the machine code over and over. I'm currently playing with a reimplementation of this where instead of jitting the machine code directly an interpreter is used whose instructions map to x86 instructions (the interpreter itself is jitted up front). I estimate it to be on a par with or even slightly faster than LuaJITs interpreter as it is direct-threaded and using only CPU registers. All in all I must say that all this is probably not worth the effort. Simple indirectly threaded interpreters implemented in C using computed gotos are already performing decently. Returns diminish pretty quickly for anything more fancy, at least in my experience.
